[package]
private = true
# SCOPE/NAME
name = "chee/roblox-tactics"
description = ""
version = "0.1.0"
license = "MIT"
authors = ["magicchex"]
repository = "https://github.com/magicchex/roblox-tactics"
homepage = "https://chee-vang.com/roblox-tactics"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = []
[dependencies]
Promise = "evaera/promise@4.0.0"

[server-dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
